### ISSUE TITLE
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa

### ISSUE THREAD

**Issue by hluetck** [simonsfoundation/CaImAn#118]
I am on OS X. Following the latest installation instruction, I get a runtime error when importing caiman:

>>> import caiman as cm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "caiman/__init__.py", line 1, in <module>
    from .base.movies import movie,load,load_movie_chain
  File "caiman/base/movies.py", line 61, in <module>
    from ..mmapping import load_memmap
  File "caiman/mmapping.py", line 20, in <module>
    import tifffile
  File "/Users/Henry/miniconda/envs/caiman/lib/python2.7/site-packages/tifffile/__init__.py", line 1, in <module>
    from .tifffile import imsave, imread, imshow, TiffFile, TiffWriter, TiffSequence, FileHandle, lazyattr, natural_sorted, decode_lzw, stripnull
  File "/Users/Henry/miniconda/envs/caiman/lib/python2.7/site-packages/tifffile/tifffile.py", line 301, in <module>
    from . import _tifffile  # noqa
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa

**Comment by agiovann** [comment]
Dear Henry,

sometimes we experience this error when there is somewhere on your path an older numpy version installed. If this is a big problem you can substitute that import with:
from skimage.external import tifffile
Let me know if this solves your issue.

Best

**Comment by agiovann** [comment]
Any update on this?
