### ISSUE TITLE
Import Error(s) - run_CNMF_patches - reloading functions from modules: motion_correct / map_reduce

### ISSUE THREAD

**Issue by colby-j-wise** [simonsfoundation/CaImAn#86]
Hi @agiovann I started getting a error during the merging step (run_CNMF_patches) - specifically when calling cnmf.map_reduce. Strangely when trying to load functions back into module I am experiencing "ImportError: No module named caiman.source_extraction.cnmf.map_reduce". Previous to this I also encountered a  "ImportError: No module named caiman.motion_correction". 

Clearly in order to get to this stage in the pipeline both of these models had have loaded correctly. Why would they not load correctly upon reload from stated path?

Error Stack Below: 
`(caiman_env) LSKI1580:CaImAn johnsenh$ python AG30HZ_pipeline_new2.py
Not IPYTHON
Bokeh could not be loaded. Either it is not installed or you are not running within a notebook
numba not found
/Users/johnsenh/Desktop/Colby_Research/CaImAn/7_5-31-16-ScatterOne/TSeries-12092015-1509-006_Cycle00001_Element00001.h5
Supposedly using 8 processors
fname_new: TSeries-12092015-1509-006_Cycle00001_Element000010000_d1_256_d2_256_d3_1_order_C_frames_27100_.mmap
/Users/johnsenh/anaconda2/envs/caiman_env/lib/python2.7/site-packages/past/utils/__init__.py:95: RuntimeWarning: invalid value encountered in divide
  return a / b
Using Ain
(27100, 256, 256)
using 8 processes
using 4000 pixels per process
using 20000 block_size
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 30)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 30)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 30)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 30)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 30)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 30)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 30)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 30)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 30)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 31)
(31, 30)
(30, 31)
(30, 31)
(30, 31)
(30, 31)
(30, 31)
(30, 31)
(30, 31)
(30, 31)
(30, 31)
(30, 31)
(30, 30)
Something went wrong
You may think that it went well but reality is harsh
Traceback (most recent call last):
  File "AG30HZ_pipeline_new2.py", line 380, in <module>
    cnm = cnm.fit(images)
  File "/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 367, in fit
    gnb=self.gnb)
  File "/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 227, in run_CNMF_patches
    file_res = dview.map_sync(cnmf_patches, args_in)
  File "/Users/johnsenh/anaconda2/envs/caiman_env/lib/python2.7/site-packages/ipyparallel/client/view.py", line 342, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "<decorator-gen-128>", line 2, in map
  File "/Users/johnsenh/anaconda2/envs/caiman_env/lib/python2.7/site-packages/ipyparallel/client/view.py", line 50, in sync_results
    ret = f(self, *args, **kwargs)
  File "/Users/johnsenh/anaconda2/envs/caiman_env/lib/python2.7/site-packages/ipyparallel/client/view.py", line 615, in map
    return pf.map(*sequences)
  File "/Users/johnsenh/anaconda2/envs/caiman_env/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 285, in map
    return self(*sequences, __ipp_mapping=True)
  File "<decorator-gen-118>", line 2, in __call__
  File "/Users/johnsenh/anaconda2/envs/caiman_env/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 76, in sync_view_results
    return f(self, *args, **kwargs)
  File "/Users/johnsenh/anaconda2/envs/caiman_env/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 271, in __call__
    return r.get()
  File "/Users/johnsenh/anaconda2/envs/caiman_env/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 167, in get
    raise self.exception()
ipyparallel.error.CompositeError: one or more exceptions from call to method: cnmf_patches
[0:apply]: ImportError: No module named caiman.source_extraction.cnmf.map_reduce
[1:apply]: ImportError: No module named caiman.source_extraction.cnmf.map_reduce
[2:apply]: ImportError: No module named caiman.source_extraction.cnmf.map_reduce
[3:apply]: ImportError: No module named caiman.source_extraction.cnmf.map_reduce
.... 4 more exceptions ...`

**Comment by colby-j-wise** [comment]
Hi,

Was able to resolve this by updating PYTHONPATH in ~/.bash_profile then restarting terminal. I also updated in Spyder Path Command Prompt given Spyder did not recognize ~/.bash_profile

Ref: https://stackoverflow.com/questions/3387695/add-to-python-path-mac-os-x
